version: '3.8'

services:
  redis:
    image: redis:alpine
    restart: always
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5
    command: ["redis-server", "--timeout", "0"]

  postgres:
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: employees_db
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d employees_db"]
      interval: 5s
      timeout: 3s
      retries: 5

  bot:
    build: .
    restart: always
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    environment:
      DATABASE_URL: "postgres://user:password@postgres:5432/employees_db?sslmode=disable"
      REDIS_URL: "redis://redis:6379"
    env_file:
      - .env
    working_dir: /app
    entrypoint: ["/app/bot-entrypoint.sh"]